### ISSUE TITLE
Installation Invalid Syntax Python

### ISSUE THREAD

**Issue by lovgrandma** [pgvector/pgvector#470]
Having issues with installation on Windows machine at this part.

See python version:
python --version
Python 3.10.1

See issue below:

$ nmake /F Makefile.win

Microsoft (R) Program Maintenance Utility Version 14.34.31937.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        copy sql\vector.sql sql\vector--0.6.0.sql
Traceback (most recent call last):
  File "C:\Users\Jesse\Anaconda3\pkgs\python-3.6.3-h9e2ca53_1\Lib\copy.py", line 52, in <module>
    import weakref
  File "C:\Users\Jesse\Anaconda3\pkgs\python-3.6.3-h9e2ca53_1\Lib\weakref.py", line 50
    .format(type(meth))) from None
                            ^
SyntaxError: invalid syntax
NMAKE : fatal error U1077: 'C:\Users\Jesse\Anaconda3\pkgs\python-3.6.3-h9e2ca53_1\Lib\copy.PY' : return code '0x1'
Stop.

**Comment by lovgrandma** [comment]
Thankyou @ankane Installing newest python from official and uninstall anaconda3 immediately produced better results

A couple warnings:

src\vector.c(885): warning C4141: 'dllexport': used more than once
src\vector.c(898): warning C4141: 'dllexport': used more than once
src\vector.c(911): warning C4141: 'dllexport': used more than once
src\vector.c(924): warning C4141: 'dllexport': used more than once
src\vector.c(937): warning C4141: 'dllexport': used more than once
src\vector.c(950): warning C4141: 'dllexport': used more than once
src\vector.c(963): warning C4141: 'dllexport': used more than once
src\vector.c(976): warning C4141: 'dllexport': used more than once
src\vector.c(1037): warning C4141: 'dllexport': used more than once
src\vector.c(1107): warning C4141: 'dllexport': used more than once

but did complete nmake /F Makefile.win
and
nmake /F Makefile.win install
