### ISSUE TITLE
Intermittent timeout on getting nearest neighbors by L2 distance

### ISSUE THREAD

**Issue by mr-shevchenko** [pgvector/pgvector#564]
Hello!

Windows Server 2022 Standard 21H2
PostgreSQL 16.1, compiled by Visual C++ build 1937, 64-bit
vector extension 0.5.1

.NET 8
[https://www.nuget.org/packages/Pgvector/0.2.0](https://www.nuget.org/packages/Pgvector/0.2.0)
[https://www.nuget.org/packages/Npgsql/8.0.3](https://www.nuget.org/packages/Npgsql/8.0.3)

```
CREATE TABLE documents 
(
    id BIGSERIAL PRIMARY KEY,
    content TEXT, 
    n_tokens INTEGER, 
    embedding VECTOR(3072)
)
```

The documents table has been populated with ~50000 records. Embeddings have been generated with OpenAI's text-embedding-3-large model using 3072 dimensions for chunks of 2048 tokens max.

```
    int currentLength = 0;
    var results = new List<string>();

    var dataSourceBuilder = new NpgsqlDataSourceBuilder("Host=mydomain.local;Port=5432;Database=test;User Id=postgres;Password=****;Command Timeout=30;");
    dataSourceBuilder.UseVector();
    var dataSource = dataSourceBuilder.Build();

    using (var conn = dataSource.CreateConnection())
    {
        await conn.OpenAsync();
        using var cmd = conn.CreateCommand();
        cmd.CommandText = $"SELECT content, n_tokens FROM documents ORDER BY embedding <-> $1 LIMIT 100";
                    
        var param = cmd.CreateParameter();
        param.Value = new Vector(searchTextWithEmbedding.Embedding);
        cmd.Parameters.Add(param);

        using var reader = await cmd.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            currentLength += reader.GetInt32(1);
            if (currentLength > 5000) break;
            results.Add(reader.GetString(0) ?? string.Empty);
        }
    }
    return results;
```

Usually I get results in 1.5 seconds. But sometimes I get:

```
 ---> Npgsql.NpgsqlException (0x80004005): Exception while reading from stream
 ---> System.TimeoutException: Timeout during reading attempt
   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
```

PostgreSQL Server log:
```
2024-05-22 13:40:54.700 [5124] ERROR:  canceling statement due to user request
2024-05-22 13:40:54.700 [5124] STATEMENT:  SELECT content, n_tokens FROM documents ORDER BY embedding <-> $1 LIMIT 100
2024-05-22 13:40:54.701 [13952] FATAL:  terminating background worker "parallel worker" due to administrator command
2024-05-22 13:40:54.701 [13952] STATEMENT:  SELECT content, n_tokens FROM documents ORDER BY embedding <-> $1 LIMIT 100
2024-05-22 13:40:54.703 [8428] FATAL:  terminating background worker "parallel worker" due to administrator command
2024-05-22 13:40:54.703 [8428] STATEMENT:  SELECT content, n_tokens FROM documents ORDER BY embedding <-> $1 LIMIT 100
```

When this happened last time, I executed immediately this code again for the same searchTextWithEmbedding.Embedding and the execution succeeded in 24 seconds. In 30 minutes, I executed this code again for the same searchTextWithEmbedding.Embedding and the execution succeeded in 1.5 seconds.

I can increase Command Timeout to cover such cases but this workaround is not suitable for my application because timely response is required.

As I understood, the index for VECTOR(3072) is currently not possible (#461).

How can I find out the reason for this intermittent problem? Are there any suggestions to avoid the issue?

**Comment by ankane** [comment]
Hi @mr-shevchenko, you can use `EXPLAIN (ANALYZE, BUFFERS)` to debug query performance in Postgres. The difference in execution times is likely due to whether or not the table is in memory. You can use tools like [pg_prewarm](https://www.postgresql.org/docs/current/pgprewarm.html) to load the table into memory, but it may not stay based on other activity on the server.

I'd recommend making sure the server is [tuned](https://github.com/pgvector/pgvector?tab=readme-ov-file#tuning). If you're able to upgrade to pgvector 0.7.0, you can use [half-precision indexing](https://github.com/pgvector/pgvector?tab=readme-ov-file#half-precision-indexing). Otherwise, you can try [indexing subvectors](https://supabase.com/blog/matryoshka-embeddings).
