### ISSUE TITLE
SQL Error [XX000]: FATAL: failed to open bitcode file "/usr/local/lib/postgresql/bitcode/vector/src/vector.bc": No such file or directory

### ISSUE THREAD

**Issue by FrankyCTY** [pgvector/pgvector#573]
## Description

I am building a graph traversal sql query that use recursive CTE to perform the graph traversal. And for each `hop`, it will order the intermediate result set in ascending order of `cosine distance` and return only the specified `@limitPerHop` nodes (100).

But I am getting an error performing the query. **Reduce the `@limitPerHop` of each hop from 100 to 10 solves the problem but it is not what I want to do.**

I want if I am hitting some kind of limit, but I don't think the error details is giving me much hints or just I couldn't interpret it.

- Pgvector version `0.5.1`
- Vector dimensions `2000` (Embedded using text-embedding-3-large model then reduced the dimensions)
- Index: `"ix_nodes_vectors" hnsw (vectors vector_cosine_ops)`

```txt
                                    List of installed extensions
  Name   | Version |   Schema   |                            Description
---------+---------+------------+-------------------------------------------------------------------
 vector  | 0.5.1   | public     | vector data type and ivfflat and hnsw access methods
...
(3 rows)
```

```txt
                                                                 Table "public.nodes"
       Column        |           Type           | Collation | Nullable |             Default              | Storage  | Compression | Stats target | Description
---------------------+--------------------------+-----------+----------+----------------------------------+----------+-------------+--------------+-------------
 id                  | bigint                   |           | not null | generated by default as identity | plain    |             |              |
 properties          | jsonb                    |           | not null |                                  | extended |             |              |
 content             | text                     |           |          |                                  | extended |             |              |
 vectors             | vector(2000)             |           |          |                                  | extended |             |              |
```

### Error details
```txt
SQL Error [XX000]: FATAL: failed to open bitcode file "/usr/local/lib/postgresql/bitcode/vector/src/vector.bc": No such file or directory

Error position:
org.jkiss.dbeaver.model.sql.DBSQLException: SQL Error [XX000]: FATAL: failed to open bitcode file "/usr/local/lib/postgresql/bitcode/vector/src/vector.bc": No such file or directory
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:133)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeStatement(SQLQueryJob.java:614)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.lambda$2(SQLQueryJob.java:505)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.executeSingleQuery(SQLQueryJob.java:524)
	at org.jkiss.dbeaver.ui.editors.sql.execute.SQLQueryJob.extractData(SQLQueryJob.java:976)
	at org.jkiss.dbeaver.ui.editors.sql.SQLEditor$QueryResultsContainer.readData(SQLEditor.java:4155)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.lambda$0(ResultSetJobDataRead.java:123)
	at org.jkiss.dbeaver.model.exec.DBExecUtils.tryExecuteRecover(DBExecUtils.java:194)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetJobDataRead.run(ResultSetJobDataRead.java:121)
	at org.jkiss.dbeaver.ui.controls.resultset.ResultSetViewer$ResultSetDataPumpJob.run(ResultSetViewer.java:5152)
	at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:115)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:63)
Caused by: org.postgresql.util.PSQLException: FATAL: failed to open bitcode file "/usr/local/lib/postgresql/bitcode/vector/src/vector.bc": No such file or directory
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2676)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2366)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.execute(JDBCStatementImpl.java:330)
	at org.jkiss.dbeaver.model.impl.jdbc.exec.JDBCStatementImpl.executeStatement(JDBCStatementImpl.java:131)
```

### SqlQuery Example
The "variable" starts with `@` are the npgsql parameter from the example C# project.

```sql
WITH RECURSIVE search_graph AS (
    -- Base case
    SELECT
        CASE WHEN @startNodeId = e.node_id1 THEN e.node_id2 ELSE e.node_id1 END AS related_node_id,
        1 AS distance,
        1::double precision AS cosine_distance
    FROM edges AS e
    JOIN nodes AS n
    ON n.id = CASE WHEN @startNodeId = e.node_id1 THEN e.node_id2 ELSE e.node_id1 END
    WHERE (@startNodeId = e.node_id1 OR @startNodeId = e.node_id2)

    UNION

    -- Recursive case
    select * from (
    SELECT
        CASE WHEN prev_result.related_node_id = e.node_id1 THEN e.node_id2 ELSE e.node_id1 END AS related_node_id,
        prev_result.distance + 1 AS distance,
        n.vectors <=> '{embedding}'::vector AS cosine_distance
    FROM edges AS e
    JOIN search_graph AS prev_result
    ON (prev_result.related_node_id = e.node_id1 OR prev_result.related_node_id = e.node_id2)
    JOIN nodes AS n
    ON n.id = CASE WHEN prev_result.related_node_id = e.node_id1 THEN e.node_id2 ELSE e.node_id1 END
    AND prev_result.distance < @maxDepths
    ORDER BY cosine_distance asc
    limit @limitPerHop
    )
)

        SELECT n.*
        FROM (
            SELECT DISTINCT sg.related_node_id, sg.cosine_distance as cosine_distance
            FROM search_graph AS sg
            order by sg.cosine_distance asc
            LIMIT @limit
        ) AS unique_nodes
        JOIN nodes AS n ON n.id = unique_nodes.related_node_id;
```

**Comment by jkatz** [comment]
@FrankyCTY Do you have `jit` set to `on`? (`SHOW jit;`)? Try disabling it and see if it fixes the query (`SET jit to off;` in the same session).

**Comment by FrankyCTY** [comment]
> @FrankyCTY Do you have `jit` set to `on`? (`SHOW jit;`)? Try disabling it and see if it fixes the query (`SET jit to off;` in the same session).

Thanks for the reply.

I am a bit new to postgres, and I have ran `SET jit to off;` and ensure `SHOW jit;` return `off` afterwards in my postgres docker instance's database, and it didn't work.

Then I tried to update the parameter in `postgresql.conf` to set the `jit` to `off`, and `related the conf` by running `SELECT pg_reload_conf();`. Afterwards the problem is resolved.

May I know how `jit` causing problem? Because I will be looking into if it will be the same problem for our managed database (Google cloud sql) as it seems also have `jit` set to `on`. Thanks a lot, I appreciate that. 

```txt
local-console=# SHOW jit;
 jit
-----
 on
(1 row)

local-console=# set jit to off;
SET
local-console=# SHOW jit;
 jit
-----
 off
(1 row)
```

**Comment by tureba** [comment]
> May I know how `jit` causing problem? Because I will be looking into if it will be the same problem for our managed database (Google cloud sql) as it seems also have `jit` set to `on`.

Likely a packaging issue on your side. You might have these sorts of errors if the bitcode file is unreadable for any reason or corrupted, or if the extension was built with a newer clang version than the server, leading to newer bitcode files to be attempted to be read the older libllvm.so that the server is linked against.

**Comment by FrankyCTY** [comment]
Thanks guys, closing the issue now 💯
