### ISSUE TITLE
[sos] connect pgvector exception

### ISSUE THREAD

**Issue by RongHouchao** [pgvector/pgvector#99]
Caused by: java.io.EOFException: null
	at org.postgresql.core.PGStream.receiveChar(PGStream.java:452) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.core.v3.ConnectionFactoryImpl.enableSSL(ConnectionFactoryImpl.java:517) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:151) ~[postgresql-42.3.1.jar:42.3.1]
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:215) ~[postgresql-42.3.1.jar:42.3.1]
	... 47 common frames omitted

pgvector: 0.4.0

**Comment by ankane** [comment]
Hi @RongHouchao, there's not enough info to reproduce, but it doesn't look like an issue with pgvector. Try using [pgvector-java](https://github.com/pgvector/pgvector-java).

**Comment by RongHouchao** [comment]
> 
I use the durid Connection pool to connect. When I connect to other postgres, I can connect, but when I connect to this pgvector, the above exception will be reported. This seems to be caused by a problem with the pgvector.

Is this related to the version of org. postgres? The pom I am using is:

<dependency>
<groupId>org.postgresql</groupId>
<artifactId>postgresql</artifactId>
<version>42.3.1</version>
</dependency>

Both versions 42.2 and 42.6 have been tried, and this exception will be reported.
